// Generated by scripts/build-real-data.mjs. Do not hand-edit.
window.BLP_REAL_DATA = {
  "generatedAt": "2026-05-27T15:15:28.055Z",
  "sources": {
    "googleDriveKnowledgeVault": {
      "label": "Google Drive Knowledge Vault",
      "url": "https://drive.google.com/drive/folders/1GoxHwnWqhhl50HvudeDnwuYBTvpXf1v-",
      "localPath": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault"
    },
    "obsidianVault": {
      "label": "Obsidian BLP Knowledge Vault",
      "vaultName": "BLP Knowledge Vault",
      "localPath": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault"
    },
    "avatarFolder": {
      "label": "BLP Agent Console - Avatars",
      "localPath": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars"
    },
    "orgCharts": {
      "label": "BLP Agent Org Chart PDFs",
      "files": [
        "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Org Chart v5.pdf",
        "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP-org-chart-v5.pdf"
      ]
    }
  },
  "avatarInventory": {
    "status": "connected",
    "localPath": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars",
    "count": 40,
    "files": [
      {
        "name": "addie.png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/addie.png",
        "ext": "png",
        "size": 1579299,
        "modifiedAt": "2026-05-20T22:23:30.821Z"
      },
      {
        "name": "anne (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/anne (1).png",
        "ext": "png",
        "size": 1473828,
        "modifiedAt": "2026-05-20T21:32:24.406Z"
      },
      {
        "name": "arnold (2).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/arnold (2).png",
        "ext": "png",
        "size": 1824081,
        "modifiedAt": "2026-05-20T22:00:04.090Z"
      },
      {
        "name": "avatar.png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/avatar.png",
        "ext": "png",
        "size": 1568396,
        "modifiedAt": "2026-05-21T00:11:47.009Z"
      },
      {
        "name": "brandy.png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/brandy.png",
        "ext": "png",
        "size": 1610964,
        "modifiedAt": "2026-05-20T22:23:07.067Z"
      },
      {
        "name": "carla.png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/carla.png",
        "ext": "png",
        "size": 1523501,
        "modifiedAt": "2026-05-20T22:42:43.603Z"
      },
      {
        "name": "chris (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/chris (1).png",
        "ext": "png",
        "size": 1526022,
        "modifiedAt": "2026-05-20T21:32:35.324Z"
      },
      {
        "name": "clara (2).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/clara (2).png",
        "ext": "png",
        "size": 1548956,
        "modifiedAt": "2026-05-20T21:32:39.476Z"
      },
      {
        "name": "cody (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/cody (1).png",
        "ext": "png",
        "size": 1573077,
        "modifiedAt": "2026-05-20T21:32:42.940Z"
      },
      {
        "name": "collette (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/collette (1).png",
        "ext": "png",
        "size": 1533354,
        "modifiedAt": "2026-05-20T21:32:46.210Z"
      },
      {
        "name": "collin (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/collin (1).png",
        "ext": "png",
        "size": 1474937,
        "modifiedAt": "2026-05-20T21:32:49.663Z"
      },
      {
        "name": "connie (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/connie (1).png",
        "ext": "png",
        "size": 1547704,
        "modifiedAt": "2026-05-20T21:32:53.212Z"
      },
      {
        "name": "dawn (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/dawn (1).png",
        "ext": "png",
        "size": 1577221,
        "modifiedAt": "2026-05-20T21:32:56.824Z"
      },
      {
        "name": "desie (3).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/desie (3).png",
        "ext": "png",
        "size": 1607950,
        "modifiedAt": "2026-05-20T22:15:51.355Z"
      },
      {
        "name": "ed (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/ed (1).png",
        "ext": "png",
        "size": 2274320,
        "modifiedAt": "2026-05-20T20:41:42.345Z"
      },
      {
        "name": "eunice.png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/eunice.png",
        "ext": "png",
        "size": 1671979,
        "modifiedAt": "2026-05-20T22:23:10.496Z"
      },
      {
        "name": "howie (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/howie (1).png",
        "ext": "png",
        "size": 1587433,
        "modifiedAt": "2026-05-20T21:33:04.013Z"
      },
      {
        "name": "hugh (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/hugh (1).png",
        "ext": "png",
        "size": 1695953,
        "modifiedAt": "2026-05-20T21:33:07.340Z"
      },
      {
        "name": "ila (2).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/ila (2).png",
        "ext": "png",
        "size": 1745688,
        "modifiedAt": "2026-05-20T22:00:00.619Z"
      },
      {
        "name": "ivory (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/ivory (1).png",
        "ext": "png",
        "size": 1526976,
        "modifiedAt": "2026-05-20T21:33:15.860Z"
      },
      {
        "name": "lee (2).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/lee (2).png",
        "ext": "png",
        "size": 1640584,
        "modifiedAt": "2026-05-20T21:59:53.392Z"
      },
      {
        "name": "libby (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/libby (1).png",
        "ext": "png",
        "size": 1582426,
        "modifiedAt": "2026-05-20T21:33:24.110Z"
      },
      {
        "name": "lindsay (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/lindsay (1).png",
        "ext": "png",
        "size": 1537038,
        "modifiedAt": "2026-05-20T21:33:27.755Z"
      },
      {
        "name": "marcus (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/marcus (1).png",
        "ext": "png",
        "size": 1525575,
        "modifiedAt": "2026-05-20T21:33:31.626Z"
      },
      {
        "name": "melody (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/melody (1).png",
        "ext": "png",
        "size": 1509338,
        "modifiedAt": "2026-05-20T21:33:34.868Z"
      },
      {
        "name": "moe (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/moe (1).png",
        "ext": "png",
        "size": 1467711,
        "modifiedAt": "2026-05-20T21:33:38.307Z"
      },
      {
        "name": "monte (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/monte (1).png",
        "ext": "png",
        "size": 1636803,
        "modifiedAt": "2026-05-20T21:33:41.591Z"
      },
      {
        "name": "penny (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/penny (1).png",
        "ext": "png",
        "size": 1318406,
        "modifiedAt": "2026-05-20T21:33:45.227Z"
      },
      {
        "name": "rajeesh (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/rajeesh (1).png",
        "ext": "png",
        "size": 1570641,
        "modifiedAt": "2026-05-20T21:33:48.790Z"
      },
      {
        "name": "reese (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/reese (1).png",
        "ext": "png",
        "size": 1497250,
        "modifiedAt": "2026-05-20T21:33:52.015Z"
      },
      {
        "name": "regis.png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/regis.png",
        "ext": "png",
        "size": 1746509,
        "modifiedAt": "2026-05-20T21:59:49.867Z"
      },
      {
        "name": "ricardo.png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/ricardo.png",
        "ext": "png",
        "size": 1801289,
        "modifiedAt": "2026-05-20T22:23:13.938Z"
      },
      {
        "name": "sally.png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/sally.png",
        "ext": "png",
        "size": 1564063,
        "modifiedAt": "2026-05-20T23:06:57.627Z"
      },
      {
        "name": "sam (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/sam (1).png",
        "ext": "png",
        "size": 1532713,
        "modifiedAt": "2026-05-20T21:33:58.638Z"
      },
      {
        "name": "sharie (2).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/sharie (2).png",
        "ext": "png",
        "size": 1849182,
        "modifiedAt": "2026-05-20T21:59:38.779Z"
      },
      {
        "name": "shirley (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/shirley (1).png",
        "ext": "png",
        "size": 1541610,
        "modifiedAt": "2026-05-20T21:34:05.359Z"
      },
      {
        "name": "tray (2).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/tray (2).png",
        "ext": "png",
        "size": 1772283,
        "modifiedAt": "2026-05-20T21:59:46.161Z"
      },
      {
        "name": "walter (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/walter (1).png",
        "ext": "png",
        "size": 1606327,
        "modifiedAt": "2026-05-20T21:34:12.092Z"
      },
      {
        "name": "warren (1).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/warren (1).png",
        "ext": "png",
        "size": 1700864,
        "modifiedAt": "2026-05-20T21:34:15.727Z"
      },
      {
        "name": "yolanda (2).png",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Console - Avatars/yolanda (2).png",
        "ext": "png",
        "size": 1929047,
        "modifiedAt": "2026-05-20T21:59:42.357Z"
      }
    ]
  },
  "knowledgeVault": {
    "status": "local-sync-connected",
    "url": "https://drive.google.com/drive/folders/1GoxHwnWqhhl50HvudeDnwuYBTvpXf1v-",
    "localPath": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault",
    "count": 279,
    "files": [
      {
        "name": "00 Nightly Backup Standard.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/00 Nightly Backup Standard.md",
        "ext": "md",
        "size": 6069,
        "modifiedAt": "2026-05-20T17:25:19.629Z"
      },
      {
        "name": "3d-scene.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/touchdesigner-mcp/references/3d-scene.md",
        "ext": "md",
        "size": 10305,
        "modifiedAt": "2026-05-13T16:36:35.263Z"
      },
      {
        "name": "advanced-usage.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/models/segment-anything/references/advanced-usage.md",
        "ext": "md",
        "size": 15803,
        "modifiedAt": "2026-05-13T16:36:35.281Z"
      },
      {
        "name": "advanced-usage.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/models/audiocraft/references/advanced-usage.md",
        "ext": "md",
        "size": 16953,
        "modifiedAt": "2026-05-13T16:36:35.280Z"
      },
      {
        "name": "advanced-usage.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/inference/llama-cpp/references/advanced-usage.md",
        "ext": "md",
        "size": 10887,
        "modifiedAt": "2026-05-13T16:36:35.278Z"
      },
      {
        "name": "airbnb.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/airbnb.md",
        "ext": "md",
        "size": 14824,
        "modifiedAt": "2026-05-13T16:36:35.252Z"
      },
      {
        "name": "airtable.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/airtable.md",
        "ext": "md",
        "size": 4300,
        "modifiedAt": "2026-05-13T16:36:35.252Z"
      },
      {
        "name": "analysis-modules.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/inference/obliteratus/references/analysis-modules.md",
        "ext": "md",
        "size": 6270,
        "modifiedAt": "2026-05-13T16:36:35.278Z"
      },
      {
        "name": "animation-design-thinking.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/manim-video/references/animation-design-thinking.md",
        "ext": "md",
        "size": 7205,
        "modifiedAt": "2026-05-13T16:36:35.246Z"
      },
      {
        "name": "animation.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/touchdesigner-mcp/references/animation.md",
        "ext": "md",
        "size": 7258,
        "modifiedAt": "2026-05-13T16:36:35.263Z"
      },
      {
        "name": "animation.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/p5js/references/animation.md",
        "ext": "md",
        "size": 10456,
        "modifiedAt": "2026-05-13T16:36:35.249Z"
      },
      {
        "name": "animations.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/manim-video/references/animations.md",
        "ext": "md",
        "size": 8836,
        "modifiedAt": "2026-05-13T16:36:35.246Z"
      },
      {
        "name": "anthology.bib.txt",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/research/research-paper-writing/templates/acl/anthology.bib.txt",
        "ext": "txt",
        "size": 1169,
        "modifiedAt": "2026-05-13T16:36:35.302Z"
      },
      {
        "name": "api-endpoints.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/research/polymarket/references/api-endpoints.md",
        "ext": "md",
        "size": 4542,
        "modifiedAt": "2026-05-13T16:36:35.298Z"
      },
      {
        "name": "api-evaluation.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/evaluation/lm-evaluation-harness/references/api-evaluation.md",
        "ext": "md",
        "size": 11114,
        "modifiedAt": "2026-05-13T16:36:35.276Z"
      },
      {
        "name": "apple.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/apple.md",
        "ext": "md",
        "size": 21122,
        "modifiedAt": "2026-05-13T16:36:35.253Z"
      },
      {
        "name": "artifacts.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/evaluation/weights-and-biases/references/artifacts.md",
        "ext": "md",
        "size": 13425,
        "modifiedAt": "2026-05-13T16:36:35.277Z"
      },
      {
        "name": "ATTRIBUTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/pixel-art/ATTRIBUTION.md",
        "ext": "md",
        "size": 2210,
        "modifiedAt": "2026-05-13T16:36:35.251Z"
      },
      {
        "name": "audio-reactive.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/touchdesigner-mcp/references/audio-reactive.md",
        "ext": "md",
        "size": 5128,
        "modifiedAt": "2026-05-13T16:36:35.263Z"
      },
      {
        "name": "autoreason-methodology.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/research/research-paper-writing/references/autoreason-methodology.md",
        "ext": "md",
        "size": 19146,
        "modifiedAt": "2026-05-13T16:36:35.299Z"
      },
      {
        "name": "benchmark-guide.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/evaluation/lm-evaluation-harness/references/benchmark-guide.md",
        "ext": "md",
        "size": 10769,
        "modifiedAt": "2026-05-13T16:36:35.276Z"
      },
      {
        "name": "block-types.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/productivity/notion/references/block-types.md",
        "ext": "md",
        "size": 3021,
        "modifiedAt": "2026-05-13T16:36:35.286Z"
      },
      {
        "name": "blp-uniform-style.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/persona-avatar-generation/references/blp-uniform-style.md",
        "ext": "md",
        "size": 2586,
        "modifiedAt": "2026-05-20T20:43:19.972Z"
      },
      {
        "name": "bmw.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/bmw.md",
        "ext": "md",
        "size": 10585,
        "modifiedAt": "2026-05-13T16:36:35.253Z"
      },
      {
        "name": "bug-report.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/github/github-issues/templates/bug-report.md",
        "ext": "md",
        "size": 469,
        "modifiedAt": "2026-05-13T16:36:35.271Z"
      },
      {
        "name": "cal.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/cal.md",
        "ext": "md",
        "size": 18582,
        "modifiedAt": "2026-05-13T16:36:35.253Z"
      },
      {
        "name": "camera-and-3d.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/manim-video/references/camera-and-3d.md",
        "ext": "md",
        "size": 4132,
        "modifiedAt": "2026-05-13T16:36:35.246Z"
      },
      {
        "name": "checklists.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/research/research-paper-writing/references/checklists.md",
        "ext": "md",
        "size": 13622,
        "modifiedAt": "2026-05-13T16:36:35.299Z"
      },
      {
        "name": "ci-troubleshooting.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/github/github-pr-workflow/references/ci-troubleshooting.md",
        "ext": "md",
        "size": 4879,
        "modifiedAt": "2026-05-13T16:36:35.271Z"
      },
      {
        "name": "citation-workflow.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/research/research-paper-writing/references/citation-workflow.md",
        "ext": "md",
        "size": 15433,
        "modifiedAt": "2026-05-13T16:36:35.299Z"
      },
      {
        "name": "claude.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/claude.md",
        "ext": "md",
        "size": 21078,
        "modifiedAt": "2026-05-13T16:36:35.253Z"
      },
      {
        "name": "clay.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/clay.md",
        "ext": "md",
        "size": 18105,
        "modifiedAt": "2026-05-13T16:36:35.253Z"
      },
      {
        "name": "clickhouse.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/clickhouse.md",
        "ext": "md",
        "size": 16180,
        "modifiedAt": "2026-05-13T16:36:35.253Z"
      },
      {
        "name": "cohere.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/cohere.md",
        "ext": "md",
        "size": 15543,
        "modifiedAt": "2026-05-13T16:36:35.254Z"
      },
      {
        "name": "coinbase.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/coinbase.md",
        "ext": "md",
        "size": 5781,
        "modifiedAt": "2026-05-13T16:36:35.254Z"
      },
      {
        "name": "colm2025_conference.pdf",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/research/research-paper-writing/templates/colm2025/colm2025_conference.pdf",
        "ext": "pdf",
        "size": 122635,
        "modifiedAt": "2026-05-13T16:36:35.304Z"
      },
      {
        "name": "color-systems.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/p5js/references/color-systems.md",
        "ext": "md",
        "size": 8647,
        "modifiedAt": "2026-05-13T16:36:35.249Z"
      },
      {
        "name": "colors.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/excalidraw/references/colors.md",
        "ext": "md",
        "size": 1777,
        "modifiedAt": "2026-05-13T16:36:35.245Z"
      },
      {
        "name": "composio.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/composio.md",
        "ext": "md",
        "size": 21732,
        "modifiedAt": "2026-05-13T16:36:35.254Z"
      },
      {
        "name": "configuration.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/email/himalaya/references/configuration.md",
        "ext": "md",
        "size": 5906,
        "modifiedAt": "2026-05-13T16:36:35.268Z"
      },
      {
        "name": "context-budget-discipline.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/software-development/subagent-driven-development/references/context-budget-discipline.md",
        "ext": "md",
        "size": 4209,
        "modifiedAt": "2026-05-13T16:36:35.311Z"
      },
      {
        "name": "conventional-commits.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/github/github-pr-workflow/references/conventional-commits.md",
        "ext": "md",
        "size": 2417,
        "modifiedAt": "2026-05-13T16:36:35.271Z"
      },
      {
        "name": "core-api.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/p5js/references/core-api.md",
        "ext": "md",
        "size": 9841,
        "modifiedAt": "2026-05-13T16:36:35.249Z"
      },
      {
        "name": "cursor.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/cursor.md",
        "ext": "md",
        "size": 19867,
        "modifiedAt": "2026-05-13T16:36:35.254Z"
      },
      {
        "name": "custom-tasks.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/evaluation/lm-evaluation-harness/references/custom-tasks.md",
        "ext": "md",
        "size": 13125,
        "modifiedAt": "2026-05-13T16:36:35.276Z"
      },
      {
        "name": "dark-mode.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/excalidraw/references/dark-mode.md",
        "ext": "md",
        "size": 2282,
        "modifiedAt": "2026-05-13T16:36:35.245Z"
      },
      {
        "name": "dat-scripting.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/touchdesigner-mcp/references/dat-scripting.md",
        "ext": "md",
        "size": 11586,
        "modifiedAt": "2026-05-13T16:36:35.263Z"
      },
      {
        "name": "decorations.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/manim-video/references/decorations.md",
        "ext": "md",
        "size": 5006,
        "modifiedAt": "2026-05-13T16:36:35.247Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/social-media/DESCRIPTION.md",
        "ext": "md",
        "size": 151,
        "modifiedAt": "2026-05-13T16:36:35.309Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/smart-home/DESCRIPTION.md",
        "ext": "md",
        "size": 123,
        "modifiedAt": "2026-05-13T16:36:35.309Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/research/DESCRIPTION.md",
        "ext": "md",
        "size": 179,
        "modifiedAt": "2026-05-13T16:36:35.297Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/productivity/DESCRIPTION.md",
        "ext": "md",
        "size": 114,
        "modifiedAt": "2026-05-13T16:36:35.283Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/productivity/ocr-and-documents/DESCRIPTION.md",
        "ext": "md",
        "size": 147,
        "modifiedAt": "2026-05-13T16:36:35.286Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/note-taking/DESCRIPTION.md",
        "ext": "md",
        "size": 146,
        "modifiedAt": "2026-05-13T16:36:35.283Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/DESCRIPTION.md",
        "ext": "md",
        "size": 162,
        "modifiedAt": "2026-05-13T16:36:35.275Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/vector-databases/DESCRIPTION.md",
        "ext": "md",
        "size": 125,
        "modifiedAt": "2026-05-13T16:36:35.282Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/training/DESCRIPTION.md",
        "ext": "md",
        "size": 150,
        "modifiedAt": "2026-05-13T16:36:35.282Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/research/DESCRIPTION.md",
        "ext": "md",
        "size": 113,
        "modifiedAt": "2026-05-13T16:36:35.281Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/models/DESCRIPTION.md",
        "ext": "md",
        "size": 253,
        "modifiedAt": "2026-05-13T16:36:35.280Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/inference/DESCRIPTION.md",
        "ext": "md",
        "size": 161,
        "modifiedAt": "2026-05-13T16:36:35.277Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/evaluation/DESCRIPTION.md",
        "ext": "md",
        "size": 126,
        "modifiedAt": "2026-05-13T16:36:35.275Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/media/DESCRIPTION.md",
        "ext": "md",
        "size": 139,
        "modifiedAt": "2026-05-13T16:36:35.274Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mcp/DESCRIPTION.md",
        "ext": "md",
        "size": 216,
        "modifiedAt": "2026-05-13T16:36:35.273Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/inference-sh/DESCRIPTION.md",
        "ext": "md",
        "size": 706,
        "modifiedAt": "2026-05-13T16:36:35.273Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/github/DESCRIPTION.md",
        "ext": "md",
        "size": 167,
        "modifiedAt": "2026-05-13T16:36:35.269Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/gifs/DESCRIPTION.md",
        "ext": "md",
        "size": 109,
        "modifiedAt": "2026-05-13T16:36:35.269Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/gaming/DESCRIPTION.md",
        "ext": "md",
        "size": 129,
        "modifiedAt": "2026-05-13T16:36:35.269Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/email/DESCRIPTION.md",
        "ext": "md",
        "size": 101,
        "modifiedAt": "2026-05-13T16:36:35.268Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/domain/DESCRIPTION.md",
        "ext": "md",
        "size": 1142,
        "modifiedAt": "2026-05-13T16:36:35.268Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/diagramming/DESCRIPTION.md",
        "ext": "md",
        "size": 159,
        "modifiedAt": "2026-05-13T16:36:35.267Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/data-science/DESCRIPTION.md",
        "ext": "md",
        "size": 137,
        "modifiedAt": "2026-05-13T16:36:35.266Z"
      },
      {
        "name": "DESCRIPTION.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/DESCRIPTION.md",
        "ext": "md",
        "size": 116,
        "modifiedAt": "2026-05-13T16:36:35.225Z"
      },
      {
        "name": "distributed-eval.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/evaluation/lm-evaluation-harness/references/distributed-eval.md",
        "ext": "md",
        "size": 11426,
        "modifiedAt": "2026-05-13T16:36:35.276Z"
      },
      {
        "name": "dogfood-report-template.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/dogfood/templates/dogfood-report-template.md",
        "ext": "md",
        "size": 1528,
        "modifiedAt": "2026-05-13T16:36:35.268Z"
      },
      {
        "name": "drive-recipes.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/productivity/google-workspace/references/drive-recipes.md",
        "ext": "md",
        "size": 3732,
        "modifiedAt": "2026-05-20T23:07:22.586Z"
      },
      {
        "name": "editing.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/productivity/powerpoint/editing.md",
        "ext": "md",
        "size": 6885,
        "modifiedAt": "2026-05-13T16:36:35.287Z"
      },
      {
        "name": "elevenlabs.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/popular-web-designs/templates/elevenlabs.md",
        "ext": "md",
        "size": 15978,
        "modifiedAt": "2026-05-13T16:36:35.254Z"
      },
      {
        "name": "equations.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/creative/manim-video/references/equations.md",
        "ext": "md",
        "size": 6086,
        "modifiedAt": "2026-05-13T16:36:35.247Z"
      },
      {
        "name": "example_paper.pdf",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/research/research-paper-writing/templates/icml2026/example_paper.pdf",
        "ext": "pdf",
        "size": 193509,
        "modifiedAt": "2026-05-13T16:36:35.307Z"
      },
      {
        "name": "examples.md",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/Shared drives/BLP Knowledge Vault/Vault/80 Agents (OpenClaw)/Lindsay/current/skills/mlops/research/dspy/references/examples.md",
        "ext": "md",
        "size": 18983,
        "modifiedAt": "2026-05-13T16:36:35.282Z"
      }
    ]
  },
  "orgCharts": {
    "status": "connected",
    "count": 2,
    "files": [
      {
        "name": "BLP Agent Org Chart v5.pdf",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP Agent Org Chart v5.pdf",
        "ext": "pdf",
        "size": 302799,
        "modifiedAt": "2026-05-21T00:38:19.535Z"
      },
      {
        "name": "BLP-org-chart-v5.pdf",
        "path": "/Users/blpadmin/Library/CloudStorage/GoogleDrive-lindsay@brighamlarsonpianos.com/My Drive/BLP-org-chart-v5.pdf",
        "ext": "pdf",
        "size": 91855152,
        "modifiedAt": "2026-05-21T00:34:00.655Z"
      }
    ]
  }
};
